### ISSUE TITLE
Add feature to downshift mixed-case username identifiers 

### ISSUE THREAD

**Issue by ASunc** [boylesoftware/tomcat-oidcauth#11]
When using email as usernameClaim, at least Azure AD seems to have different styles for email addresses. Some people have first.last@example.com and other ones have First.Last@example.com. As tomcat handles username in case-sensitive manner, this causes easily situations where user is not found after successful authentication (just because of different way of typing upper/lowercase characters).

Would it be possible to have a parameter to Valve that would downshift usernames (for example) before passing them to tomcat ?

**Comment by levahim** [comment]
Closing. Please reopen if still an issue and provide rationale.
