### ISSUE TITLE
Jboss Web Server (JWS) 3.0 - Version 2.2.2 - issue with JWS 3.0 (Tomcat 8.0) - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jeffreedzbc** [boylesoftware/tomcat-oidcauth#13]
Version 2.2.2

I have been testing your sample application for this plugin with JWS 3.0 with bundled Tomcat 8.0 (using the 8.0 jar).  I encounter the failure "java.lang.NoSuchMethodError org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.checkForCachedAuthentication" when attempting to access a secure page.

I downloaded standalone Tomcat 8.5 and the plugin works fine with the same sample application configuration (using the 8.5 jar)

I've downloaded standalone Tomcat 8.0 and it is working fine, so the issue appears isolated to the JWS 3.0 Tomcat 8.0 version.

Can you address the incompatibility the JWS 3.0 bundled Tomcat 8.0 version to allow it to function?

**Error in browser when attempting to access the secure page-a link in the sample app:**

> HTTP Status 500 - org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.checkForCachedAuthentication(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;Z)Z
> type Exception report
> 
> message org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.checkForCachedAuthentication(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;Z)Z
> 
> description The server encountered an internal error that prevented it from fulfilling this request.
> 
> exception
> 
> java.lang.NoSuchMethodError: org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.checkForCachedAuthentication(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;Z)Z
> 	org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.performAuthentication(BaseOpenIDConnectAuthenticator.java:807)
> 	org.bsworks.catalina.authenticator.oidc.tomcat80.OpenIDConnectAuthenticator.authenticate(OpenIDConnectAuthenticator.java:27)
> 	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:576)
> 	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
> 	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
> 	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
> 	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1103)
> 	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
> 	org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:285)
> 	org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2419)
> 	org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2408)
> 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	java.lang.Thread.run(Thread.java:745)
> note The full stack trace of the root cause is available in the Apache Tomcat/8.0.18 logs.
> 
> Apache Tomcat/8.0.18

**Comment by levahim** [comment]
JWS 3.0 uses Apache Tomcat 8.0.18. This authenticator requires Tomcat 8.0.21 or higher. You've got two options: replace Tomcat 8.0.18 that comes with JWS 3.0 with a newer version, or upgrade to JWS 3.1, which uses Tomcat 8.0.36.
