### ISSUE TITLE
Fails to work with AWS Cognito User Pool authentication !

### ISSUE THREAD

**Issue by rogerramesh** [boylesoftware/tomcat-oidcauth#15]
Folks,

Tested with Sample app,  the authentication didn't happen.  All I could see was Authentication Error..something went wrong with authentication.
Do we have any specific pre-reqs to work with AWS Cognito ?
Regards
Roger

**Comment by levahim** [comment]
Closing as unreproducable. Please reopen if still an issue and provide more detail.
