### ISSUE TITLE
Authentication Error - tomcat 9

### ISSUE THREAD

**Issue by joannazgao** [boylesoftware/tomcat-oidcauth#16]
I have installed your sample oidcauth, but got an authentication error after IDP authenticated my login account. Where is the authenticator debug log located? 

Here is the URL:
https://utlxdev0484.cloud.internal:8443/oidcauth/j_security_check?code=MTJjYzgyOGMtYzJhMy00NTEwLWI0ZTAtMWQ3YzBiNjZlNDcyLWJYVHdJTDgyKzBTa0I1THNwR1ZDYm92SmJiMD0%3D&state=0Zfccc8b93c4950accb47b5b5084d256e6

Error message:
Authentication Error
Something went wrong with the authentication. Check the authenticator debug log for details.

Go Back Home

**Comment by levahim** [comment]
The authenticator uses Tomcat's JULI for logging. Enable `FINE` logging level for `org.bsworks` and `org.apache.catalina.authenticator`.

**Comment by joannazgao** [comment]
Here is what we got:
02-May-2019 13:14:50.884 FINE [https-jsse-nio-8443-exec-8] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.process  AuthResponse the ID token issuer does not match

**Comment by joannazgao** [comment]
I got it working now :) Thanks

**Comment by mallikarjun-sh** [comment]
Hi joannazgao,

I am also facing the same issue, can you please tell me what was the fix?

Error message:
Authentication Error

Something went wrong with the authentication. Check the authenticator debug log for details.
Go Back Home

-Mallikarjun
