### ISSUE TITLE
get value from user attributes from IDP

### ISSUE THREAD

**Issue by joannazgao** [boylesoftware/tomcat-oidcauth#17]
Hello,
        We are trying to see if we can get some specific user attributes from IDP.  I am planning to add those extra attributes into additionalScopes. My question is:  Are those values stored in  javax.security.Subject, header, Session, etc.? Basically how to retrieve those value within application?

Thanks,
Joanna

**Comment by levahim** [comment]
See Authorization Info section in the README. The `idToken` field is the JWT. You can decode it and get the info from its payload.
