### ISSUE TITLE
Fail to connect to Google Account by OpenID Connect with Tomcat 9.0

### ISSUE THREAD

**Issue by ShirleyAu** [boylesoftware/tomcat-oidcauth#18]
I am using Tomcat 9.0 at 64 Bit window 7. I try to let my Tomcat to connect to Google Account by OpenID connect. However, it does not work.  Can anyone help me?

My setting:
content.xml

<Valve className="org.bsworks.catalina.authenticator.oidc.tomcat90.OpenIDConnectAuthenticator"
 
       providers="[       
            {
               name: Google,
               issuer: https://accounts.google.com,
               clientId: xxxxxxxxxxxxxxxxxxxxxxx,
               clientSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
               extraAuthEndpointParams: {
                   hd: abc.com
               }
           }
       ]"
/>
 

at web.xml
add this
 
<login-config>
    <auth-method>FORM</auth-method>
    <realm-name>My Application</realm-name>
    <form-login-config>
        <form-login-page>/OIDC/login.jsp</form-login-page>
        <form-error-page>/OIDC/login-error.jsp</form-error-page>
    </form-login-config>
</login-config>
 

JSP Code
/OIDC/login.jsp
 
<h1>Login</h1>
<form method="post" action="j_security_check">
  <ul>
    <li>
      <label for="usernameInput">Username</label>
      <div><input id="usernameInput" type="text" name="j_username"></div>
    </li>
    <li>
      <label for="passwordInput">Password</label>
      <div><input id="passwordInput" type="password" name="j_password"></div>
    </li>
    <li>
      <button type="submit">Submit</button>
    </li>
  </ul>
</form>
 
 
 
/OIDC/login-error.jsp
 
<h1>Login Error Page</h1>
 
 
then restart the tomcat
 
Then, at UI
 
http://localhost/OIDC/login.jsp
 
I press username and password for a google account. Then, it will forward to http://localhost/OIDC/j_security_check.
 
So, it is means not work?????? Am I do it wrongly?

**Comment by levahim** [comment]
This is a application configuration issue. Does not describe any problem with the authenticator. Closing as stale. Please reopen if I'm missing something and you do identify a problem with the authenticator.
