### ISSUE TITLE
callback to Tomcat 9

### ISSUE THREAD

**Issue by ShirleyAu** [boylesoftware/tomcat-oidcauth#21]
I try to use openid connect with Tomcat 9.0. 

I send a request like this
https://federate.abcd.com/as/authorization.oauth2?client_id=aaa&redirect_uri=http://localhost:20000/Callback&response_type=code&scope=openid%20email%20profile&state=abc

After login, it will redirect back to 
http://localhost:20000/Callback?code=Mqwo3SSfAAp6uFfOViUfIxxxxxxxxxxxxxxxxxx&state=abc

However, what next?

 I do not understand how to decode the "code"? 
how to write the callback?
how to get the email from code?

**Comment by levahim** [comment]
You don't need to decode the code. The authenticator does it. The email you don't get from the code, you get it from the JWT (the id token) that the authenticator provides to the webapp after successful authentication.

**Comment by ShirleyAu** [comment]
thx, but how to do that? what I need to add to my Tomcat?

**Comment by levahim** [comment]
If you configure it correctly, it should just work. You don't need any auth specific code in your app or add anything else to Tomcat besides the authenticator.

**Comment by ShirleyAu** [comment]
Thanks. I really think I have not set it correct. So, let me explain what I have set, can you pin out what's i am wrong

1) at context.xml

<Valve className="org.bsworks.catalina.authenticator.oidc.tomcat90.OpenIDConnectAuthenticator"

       providers="[	   
			{
               name: Infineon,
               issuer: https://accounts.google.com,
               clientId: 59643334143-5f5tfjo7a9768u169mcv55ge69f7ilpk.apps.googleusercontent.com,
               clientSecret: XXXXXXXXXXXXXXXXXXXXXXX,
               extraAuthEndpointParams: {
                   hd: abc.com
               }
			}
       ]"
 />

2) put tomcat-oidcauth-2.2.3-tomcat90.jar at lib folder

3) Restart tomcat

4) access URL: 
https://accounts.google.com/o/oauth2/auth?client_id=59643334143-5f5tfjo7a9768u169mcv55ge69f7ilpk.apps.googleusercontent.com&redirect_uri=http://localhost:20000/Callback&response_type=code&scope=openid%20email%20profile

5) After login at Google, it will redirect to 
http://localhost:20000/Callback?code=4/iAGU1DL_fwQCUEm9JPjQhUOy25oaW7FneoC6G1GLceqNBq_6QuDS7bKADupANyAh2GrbUytwBHdg6x9ZoKrHzZ4&scope=email+profile+https://www.googleapis.com/auth/userinfo.profile+openid+https://www.googleapis.com/auth/userinfo.email&authuser=0&session_state=ca7ef0f383abfb8cba1f3d4097898d91e5ed05d1..067e&prompt=none

As you said I do not need to write any code at Callback, So, I remove the page. Now, it will have error HTTP Status 404 – Not Found.

So, my questions is my step correct or not? What should I do for the callback?

**Comment by ShirleyAu** [comment]
I mainly want to get the email after the account login, can you teach me how to get the email?

**Comment by ShirleyAu** [comment]
anyone know how to set the callback and how to decode the code?

**Comment by mikekonikoff** [comment]
@ShirleyAu I went through same struggle today. In my case it turned out to be a missing trailing slash at end of issuer URL. Once there, everything worked perfectly transparently, you don't have to mess with the code param.

Your case is probably different. BEST thing you can do is add this to your tomcat/conf/logging.properties and restart tomcat:
org.bsworks.catalina.authenticator.level=FINE

Now you will see all sorts of stuff in the output log that should help diagnose your issue.

I also added in the src to myeclipse and was able to step through the authentication method. But all I really needed was the log output telling me that the issuer didn't match :-)

**Comment by ShirleyAu** [comment]
I add servlet like this.

 <servlet>
      <servlet-name>OAuth2Servlet</servlet-name>
      <servlet-class>tools.OIDC.auth.OAuth2Servlet</servlet-class>
   </servlet>
 
   <servlet-mapping>
      <servlet-name>OAuth2Servlet</servlet-name>
      <url-pattern>/Callback</url-pattern>
   </servlet-mapping>


OAuth2Servlet.java

@SuppressWarnings("serial")
// START:get
public class OAuth2Servlet extends HttpServlet
{
  protected void doGet( HttpServletRequest req, HttpServletResponse res )
      throws IOException
  {
    if( !hasError(req, res) ) {
      res.sendRedirect( doAuth(req) );
    }
  }
// END:get  
  private boolean hasError( HttpServletRequest req, HttpServletResponse res )
      throws IOException
  {
    String error = req.getParameter( "error" );
    if( error != null ) {
      res.getWriter().write( "Sorry, auth failed because: " + error );
      return true;
    }
    return false;
  }
  
// START:auth
  private String doAuth(HttpServletRequest req)
      throws IOException
  {
    String authCode = req.getParameter( "code" );
    System.out.println("authCode: " + authCode);

    String callbackUri = AuthUtils.fullUrl( req, AuthUtils.OAUTH2_PATH );
    System.out.println("callbackUri: " + callbackUri);

    // We need a flow no matter what to either redirect or extract information
    AuthorizationCodeFlow flow = AuthUtils.buildCodeFlow();

    // Without a response code, redirect to Google's authorization URI
    if( authCode == null ) {
      return flow.newAuthorizationUrl().setRedirectUri( callbackUri ).build();
    }

    // With a response code, store the user's credential, and 
    // set the user's ID into the session
    GoogleTokenResponse tokenRes = getTokenRes( flow, authCode, callbackUri );

    // Extract the Google user ID from the ID token in the auth response
    String userId = getUserId( tokenRes );
    System.out.println("userId: " + userId);

    // Store the user if for the session
    SessionUtils.setUserId( req, userId );

    // Store the credential with the user
    flow.createAndStoreCredential( tokenRes, userId );

    return "/";
  }
// END:auth

  /**
   * Makes a remote call to the Google Auth server to authorize the grant code,
   * in order to issue a request token.
   * @param flow
   * @param code
   * @param callbackUri
   * @return
   * @throws IOException
   */
  private GoogleTokenResponse getTokenRes( AuthorizationCodeFlow flow, String code, String callbackUri ) 
      throws IOException
  {
    AuthorizationCodeTokenRequest tokenReq = flow
        .newTokenRequest( code )
        .setRedirectUri( callbackUri );

    TokenResponse tokenRes = tokenReq.execute();
    
    return (GoogleTokenResponse)tokenRes;
  }

  /**
   * Extract the Google user ID from the ID token in the auth response
   */
  private String getUserId( GoogleTokenResponse tokenRes )
      throws IOException
  {
    return tokenRes.parseIdToken().getPayload().getUserId();
  }


Restart the Tomcat,

After login at google, it will redirect to http://localhost:20000/Callback?code=4/jwGw5w7Z-L7RdpaHrFq7vUOQG0YZPZ-RPkTnJuGl1ddI4XoGboutBjT4EDgOH6SJtfQvUPGk61gGYUYUn-ow_-4&scope=email+profile+https://www.googleapis.com/auth/userinfo.email+openid+https://www.googleapis.com/auth/userinfo.profile&authuser=0&session_state=7cb3127ec3ba6acba5d557780853e6322ce87623..e648&prompt=none

Then, have error

com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
	com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:800)
	com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:112)
	com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:40)
	com.google.api.client.extensions.appengine.http.UrlFetchRequest.execute(UrlFetchRequest.java:74)
	com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
	com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:158)
	com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:79)
	tools.OIDC.auth.OAuth2Servlet.getTokenRes(OAuth2Servlet.java:94)
	tools.OIDC.auth.OAuth2Servlet.doAuth(OAuth2Servlet.java:62)
	tools.OIDC.auth.OAuth2Servlet.doGet(OAuth2Servlet.java:27)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)


Anyone know what's wrong?

**Comment by levahim** [comment]
This is not related to the authenticator itself. Should be discussed outside the authenticator issue tracking. This issue tracking space is for reporting bugs in the authenticator and for requesting new features. Closing it.
