### ISSUE TITLE
Tomcat 8.5.46 changes breaks OIDC valve

### ISSUE THREAD

**Issue by amergey** [boylesoftware/tomcat-oidcauth#23]
In tomcat 8.5.46, they change behavior of Base64 utility, it is not longer "url safe" 
so OIDC valve is failing with 

> java.security.SignatureException: Signature length not correct: got 243 but was expecting 252
> 		at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
> 		at java.security.Signature$Delegate.engineVerify(Signature.java:1222)
> 		at java.security.Signature.verify(Signature.java:655)

		
Because of
` final byte[] idTokenSignature = Base64.decodeBase64(idTokenParts[2]); `
that is not handling signature with '-' and '_' as it was before.

They will restore "url safe" decode method in 8.5.47 but with another signature:
org.apache.tomcat.util.codec.binary.Base64.decodeBase64URLSafe(String)
But changing that would break the ability of using the valve with older version of tomcat.

Maybe code should be change, to use java.util.Base64.getUrlDecoder().decode(str), so it will work on every version of tomcat

**Comment by amergey** [comment]
Base64 is currently used in org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator 
and org.bsworks.catalina.authenticator.oidc.JWKSet

**Comment by levahim** [comment]
Fixed in release 2.2.5. Uses java.util.Base64 now.
