### ISSUE TITLE
Tomcat Authentication Error on tomcat 9.0.27 and 8.5.47

### ISSUE THREAD

**Issue by mallikarjun-sh** [boylesoftware/tomcat-oidcauth#24]
I tried with sample application and I am getting the Authentication error . 

Error Message:
Authentication Error

Something went wrong with the authentication. Check the authenticator debug log for details.
Go Back Home

URL: https://mypc.abc.com:8443/demo/j_security_check?code=AQABAAIAAACQN9

Logs:
20-Oct-2019 11:47:11.682 FINE [https-openssl-nio-8443-exec-8] org.apache.catalina.authenticator.AuthenticatorBase.invoke  Failed authenticate() test

another Query:
In Azure portal if I configure https://mypc.abc.com:8443/demo/j_security_check then only the authentication is taking place. Do we really need to add j_security_check for authentication?

-Mallikarjun

**Comment by amergey** [comment]
You are probably hitting the issue I raised here: #23 
OIDC valve is broken in last tomcat versions

**Comment by levahim** [comment]
Please try the latest release of the authenticator v2.2.5. It has been adjusted to work with the latest Tomcat 9.0 and 8.5 versions.
Re. another query: Not sure I get the question. Can you explain further?

**Comment by mallikarjun-sh** [comment]
I tried using latest release of the authenticator v2.2.5 but issue is not resolved. 

Valve config in context.xml:
<Valve className="org.bsworks.catalina.authenticator.oidc.tomcat85.OpenIDConnectAuthenticator"
               providers="
                [
                    {
                        name:'Microsoft Azure AD',
                        issuer:https://login.microsoftonline.com/050a4b73-4cd8-4da5-bf80-6c7ff132sdf/,
                        clientId:0afdda49-c961-4b0a-be74-679aeewes3be,
                        clientSecret:heV?cD4?rA@UH1yAut7Le2Jadsa20P=XE1
                    }
                ]"
				usernameClaim="email" additionalScopes="email" noForm="true"
		/>

Log:
24-Oct-2019 21:17:38.541 FINE [https-openssl-nio-443-exec-6] org.apache.catalina.authenticator.AuthenticatorBase.invoke  Not subject to any constraint
24-Oct-2019 21:17:39.637 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.authenticator.AuthenticatorBase.invoke Security checking request GET /kakati2/secure/page-a
24-Oct-2019 21:17:39.637 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.realm.RealmBase.findSecurityConstraints   Checking constraint 'SecurityConstraint[Secure Pages]' against GET /secure/page-a --> true
24-Oct-2019 21:17:39.638 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.realm.RealmBase.findSecurityConstraints   Checking constraint 'SecurityConstraint[Secure Pages]' against GET /secure/page-a --> true
24-Oct-2019 21:17:39.639 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.authenticator.AuthenticatorBase.invoke  Calling hasUserDataPermission()
24-Oct-2019 21:17:39.643 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.realm.RealmBase.hasUserDataPermission   User data constraint already satisfied
24-Oct-2019 21:17:39.644 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.authenticator.AuthenticatorBase.invoke  Calling authenticate()
24-Oct-2019 21:17:39.649 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.authenticator.FormAuthenticator.forwardToLoginPage Forwarding request for [/kakati2/secure/page-a] made with method [GET] to login page [/WEB-INF/jsps/login.jsp] of context [/kakati2] using request method GET
24-Oct-2019 21:17:39.706 FINE [https-openssl-nio-443-exec-3] org.apache.catalina.authenticator.AuthenticatorBase.invoke  Failed authenticate() test
24-Oct-2019 21:17:48.582 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.authenticator.AuthenticatorBase.invoke Security checking request GET /kakati2/j_security_check
24-Oct-2019 21:17:48.583 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.realm.RealmBase.findSecurityConstraints   Checking constraint 'SecurityConstraint[Secure Pages]' against GET /j_security_check --> false
24-Oct-2019 21:17:48.585 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.realm.RealmBase.findSecurityConstraints   Checking constraint 'SecurityConstraint[Secure Pages]' against GET /j_security_check --> false
24-Oct-2019 21:17:48.589 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.realm.RealmBase.findSecurityConstraints   Checking constraint 'SecurityConstraint[Secure Pages]' against GET /j_security_check --> false
24-Oct-2019 21:17:48.590 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.realm.RealmBase.findSecurityConstraints   Checking constraint 'SecurityConstraint[Secure Pages]' against GET /j_security_check --> false
24-Oct-2019 21:17:48.590 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.realm.RealmBase.findSecurityConstraints   No applicable constraint located
24-Oct-2019 21:17:48.591 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.authenticator.AuthenticatorBase.invoke  Calling authenticate()
24-Oct-2019 21:17:49.015 FINE [https-openssl-nio-443-exec-4] org.apache.catalina.authenticator.AuthenticatorBase.invoke  Failed authenticate() test
I am using Microsoft Azure.

Another Query:
I am using Microsoft Azure as OP.  I have configured the below Redirect URLs with j_security_check. 
If I don't configure j_security_check the authentication code is not getting generated and below error message is coming. As per the documentation
we don't need to configure j_security_check in Redirect URLs in Azure portal.
 
Sorry, but we’re having trouble signing you in.
AADSTS50011: The reply url specified in the request does not match the reply urls configured for 
the application: '0afdda49-c961-4b0a-be74-679aee17abbe'. 
 Request Id: 9cdf8862-d33e-4a3e-b47e-d778f866c900
Correlation Id: 1ed668d9-c3ce-4264-ae73-49bce4525dac
Timestamp: 2019-10-24T15:54:17Z
Message: AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '0afdda49-c961-4b0a-be74-679aee17abbe'.
Advanced diagnostics: Enable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.
 
 but as per the documentation we don't need configure j_security_check in Redirect URLs.

Redirect URLs configured for this app:
https://mypc.abc.com:8443/demo/secure/j_security_check/
https://mypc.abc.com:8443/demo/secure/page-b
https://mypc.abc.com:8443/demo/j_security_check

**Comment by levahim** [comment]
@mallikarjun-sh , not sure to what documentation you refer when you say that j_security_check is not needed. The allowed redirect URL configured in the auth provider must be exactly the callback URL, including the path, including j_security_check.

**Comment by mallikarjun-sh** [comment]
Hi levahim,

Thank you for the immediate reply.  May be I have misunderstood but I have added the j_security_check to callback URL but after that also I am getting the below error message in log and it is redirecting error page.

org.apache.catalina.authenticator.AuthenticatorBase.invoke Failed authenticate() test

Can you verify whether my configuration in Valve is correct or not. I am not sure where exactly I am doing the mistake.

**Comment by mallikarjun-sh** [comment]
Any body reply please. I am trying this Valve based solution more than a week but not yet succeeded (tried on tomcat 8.5.47 and 9.0.27 .  I was able to authenticate using ADAL4J using Filter but this Valve based solution is not working for me.  Not sure where exactly I am doing the mistake.

**Comment by levahim** [comment]
There is not enough information in your messages to see what's happening. Unless you see exceptions in the authenticator's log, most likely you misconfigured it. The log should tell you where exactly the authentication fails.

**Comment by mallikarjun-sh** [comment]
The issue is resolved.  I have not included the /v2.0 in the issuer property because of that authentication is failing.  Valve configuration for reference.

<Valve className="org.bsworks.catalina.authenticator.oidc.tomcat90.OpenIDConnectAuthenticator"
               providers="
                [
                    {
                        name:'Microsoft Azure AD demo app',
                        issuer:https://login.microsoftonline.com/050a4b73-f132sdf/v2.0,
                        clientId:0afdda9aee17abbe23ss,
                        clientSecret:heV3cDr80P=XE1asd3
                    }
                ]"
		usernameClaim="email" additionalScopes="email"  noForm="true"
    />

**Comment by levahim** [comment]
OK, closing the issue. Note: be careful about sharing values like clientId and clientSecret in a public thread like this!
