### ISSUE TITLE
Valve is no longer working with tomcat 8.5.50

### ISSUE THREAD

**Issue by amergey** [boylesoftware/tomcat-oidcauth#25]
Upgrading to tomcat 8.5.50, the valve stop working, instead of giving access to the application, the valve is redirecting to form.
I tried to debug the cause, I do not understand why yet, but I notice the difference between previous tomcat version.
Prior to 8.5.50, after a successfull authentication the org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.performAuthentication(Request, HttpServletResponse) method was redirecting to the original URI, then 
performAuthentication is called again and following code was returning true
_// check if resubmit after successful authentication
		if (this.matchRequest(request))
			return this.processResubmit(request, response);_

in tomcat 8.5.50, matchRequest is returning false for some reasons so the valve is redirecting to form instead of the application

**Comment by amergey** [comment]
It seems the culprit is https://github.com/apache/tomcat/commit/1ecba14e690cf5f3f143eef6ae7037a6d3c16652#diff-d3a23672da52a023e04cefd774dbe896

**Comment by amergey** [comment]
A fix suggestion:
Everywhere session.setNote(Constants.FORM_PRINCIPAL_NOTE, principal); is called, call register as well should make the valve still work for old tomcat version and newser

- **com.semarchy.tool.jee.tomcat.oidc.BaseOpenIDConnectAuthenticator.reauthenticateNoCache(Request, HttpServletResponse)**

_// set principal on the session
		// for tomcat version < 8.5.50
		session.setNote(Constants.FORM_PRINCIPAL_NOTE, principal);
		// for tomcat version >= 8.5.50
		this.register(request, response, principal,
				HttpServletRequest.FORM_AUTH,
				username,
				password);_ 

- **com.semarchy.tool.jee.tomcat.oidc.BaseOpenIDConnectAuthenticator.performAuthentication(Request, HttpServletResponse)**

		_// save the authenticated principal in our session
		// for tomcat version < 8.5.50
		session.setNote(Constants.FORM_PRINCIPAL_NOTE, principal);
		// for tomcat version >= 8.5.50
		this.register(request, response, principal,
				HttpServletRequest.FORM_AUTH,
				(String) session.getNote(Constants.SESS_USERNAME_NOTE),
				(String) session.getNote(Constants.SESS_PASSWORD_NOTE));_

**Comment by adam00s** [comment]
Suggested fix was needed for 9.0 too, thank you.

**Comment by amergey** [comment]
Yes I think it is needed for all tomcat versions, as the commit breaking things is a security fix, that is currently backported in every tomcat version, including ones managed packaged by various linux distrib

**Comment by amergey** [comment]
After more thought about my proposed fix I think keeping old tomcat version compatibility is a bad idea because, this was removed from tomcat as a security fix in the first place.
so replacing 
`session.setNote(Constants.FORM_PRINCIPAL_NOTE, principal);`
with
```
this.register(request, response, principal,
				HttpServletRequest.FORM_AUTH,
				username,
				password);

```
is the thing to do not keeping both and if for some reasons someone is stuck with an old tomcat version, then he would have to keep 2.2.5 version of the valve

**Comment by levahim** [comment]
Version 2.3.0 of the authenticator addresses this issue.
