### ISSUE TITLE
CORS Issue: OPTIONS Request enforce creating a new session

### ISSUE THREAD

**Issue by hussayndabbous** [boylesoftware/tomcat-oidcauth#28]
We try to setup tomcat-oidcauth (2.2.5 or 2.3.0) to also work with CORS:

```
<Valve className="org.bsworks.catalina.authenticator.oidc.tomcat90.OpenIDConnectAuthenticator"
       allowCorsPreflight="always"
       providers="[
           {
               name: *****,
               issuer: ****************,
               clientId: *****************************,
               clientSecret: *************************
           }
       ]"
    />
```

When we send an OPTION Request to a page that is authenticated by oidcauth, tomcat creates a new session cookie and redirects to the openid login host. However tomcat reacts correct when we send an OPTIONS request to any page that is not under control of oidcauth.

Here is a snippet from the logfile that demonstrates OPTIONS requests are treated as regular requests:

```05-Mar-2020 14:23:10.401 FINE [http-nio-8487-exec-26] org.apache.catalina.authenticator.FormAuthenticator.forwardToLoginPage Forwarding request for [/******/x.jsp] made with method [OPTIONS] to login page [/*******] of context [/****] using request method GET```

A quick search within the connector sources lets us believe that OPTIONS requests are not recognized and handled as normal requests without sessionid. However its possible that our configuration is wrong. 

Any advice?

kind regards,
Hussayn

**Comment by levahim** [comment]
It must be your configuration. I used the sample webapp with both basic `FormAuthenticator` and the `OpenIDConnectAuthenticator` with `allowCorsPreflight="always"`. The behavior is identical:

```
$ curl -vk -X OPTIONS -H "Origin: null" -H "Access-Control-Request-Method: GET" https://localhost:8443/test/secure/page-a
...
> OPTIONS /test/secure/page-a HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.71.1
> Accept: */*
> Origin: null
> Access-Control-Request-Method: GET
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
< Cache-Control: private
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Allow: GET, HEAD, POST, OPTIONS
< Content-Length: 0
< Date: Sat, 01 Aug 2020 14:32:07 GMT
< 
* Connection #0 to host localhost left intact
```

So, works as expected. Closing this issue. Please reopen it if you still believe there is a problem with the authenticator. Thanks!
