### ISSUE TITLE
sample app with Azure AD

### ISSUE THREAD

**Issue by ekkelenkamp** [boylesoftware/tomcat-oidcauth#34]
Thanks for creating this nice project. It seems to be quite useful for using OIDC in classic JEE applications. I'm evaluating it for one of my webapps that uses form based authentication.

I'm trying to get the sample application working with Azure AD.
I create an azure App registration where I got a clientId and a client secret. I also used a redirect URL to http://localhost:8080

When clicking on the oidc link in the sample application, I get redirected to the Azure login. After entering the credentials, the following error is displayed in the browser:

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 

I didn't see anything in the documentation about configuring a redirect URL. Any idea what might be going wrong?

**Comment by ekkelenkamp** [comment]
After some debugging it appears https is passed as redirect URL with j_security_check.

So i configured the sample app to use https on port 8443 and added the following redirect uri to the Azure App:

https://localhost:8443/j_security_check

Now I get redirected to my app and most seems to be working, but in the end I get an authentication error:

Authentication Error
Something went wrong with the authentication. Check the authenticator debug log for details.

I enabled de logging to fine.
In the logging most looks fine. Any suggestions would be great.

17-Jul-2020 20:43:35.441 FINE [https-jsse-nio-8443-exec-5] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse decoded ID token:
    header:    {"x5t":"huN95IvPfehq34GzBDZ1GXGirnM","kid":"huN95IvPfehq34GzBDZ1GXGirnM","typ":"JWT","alg":"RS256"}
    payload:   {"sub":"vWmmOhzaLZrrjKMbVKr75D0Z7keMU4kAyat5gsmc7Y8","ver":"1.0","amr":["pwd"],"iss":"https://sts.windows.net/**********/","oid":"*******","uti":"********","given_name":"Rudie","tid":"fd1e2720-3045-45b8-8fe4-a8ae2b055d87","aud":"177ced50-3ffb-4cad-b619-cf65c92b39db","unique_name":"*********","nbf":1595011115,"idp":"live.com","rh":"0.ATAAICce_UUwuEWP5KiuKwVdh1DtfBf7P61MthnPZckrOdswACs.","name":"*******","exp":1595015015,"ipaddr":"62.251.44.155","iat":1595011115,"family_name":"********","email":"*********"}
    signature: [5, -1, -115, 81, 39, 28, 101, 77, 111, -16, 63, -29, -29, 16, -33, 61, 45, 127, -6, 97, 106, 46, 98, -117, 109, 104, 25, -90, 4, -2, -41, -37, 30, 54, 105, 88, -126, -124, -101, -122, -93, -15, 22, 47, 0, -62, -13, -120, 0, 77, -83, 77, 5, -1, -90, 68, -29, -73, 13, 122, -86, 6, 45, 66, -62, -12, -67, -4, 118, -103, -102, 54, -13, 47, 6, 63, 59, -28, 105, 62, -31, -72, 63, -114, 88, 0, -81, -121, -20, 116, -77, 18, -47, 47, -99, -12, -92, -28, 68, -124, 19, 0, -53, 9, 86, 95, 21, -8, -87, -90, 108, -57, 108, -115, 65, -20, 36, 30, 4, -122, 47, -9, 28, -48, 90, 41, 67, 65, 94, -82, 9, 85, -69, 59, 97, 25, 97, -125, 82, -49, -84, 28, -15, 109, -50, -117, -61, -96, -50, -76, -114, 4, -98, 55, -19, 82, -107, 111, -3, 54, -9, 78, 59, 97, -33, 127, -26, 85, -63, 72, -91, -5, 38, -76, -62, -29, -34, -41, 19, -45, 9, -121, -64, 41, -76, -51, 93, 77, 78, 82, -75, -98, 75, 22, -56, -116, 3, 43, -40, -47, -39, 65, 69, 80, -40, -32, -124, -82, 57, 64, -63, -99, -88, -72, 107, 15, 80, 80, 37, -12, -58, -28, -91, 80, -85, -58, 114, 33, 82, 118, -50, -126, -113, -96, -45, -62, 106, -84, -46, 101, 83, 17, 119, 28, 41, 16, -48, 37, -74, -128, -123, 81, -8, -51, -115, 100]

17-Jul-2020 20:43:35.442 FINE [https-jsse-nio-8443-exec-5] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse signature validated successfully
17-Jul-2020 20:43:35.442 FINE [https-jsse-nio-8443-exec-5] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse authenticating user "*****@hotmail.com"
17-Jul-2020 20:43:35.442 FINE [https-jsse-nio-8443-exec-5] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse failed to authenticate the user in the realm

**Comment by ekkelenkamp** [comment]
It turns out the issue is the same as: https://github.com/boylesoftware/tomcat-oidcauth/issues/7
I added my user to the users.xml and everything works fine.
As described in that issue, I don't want to add users explicitly and always allow login.
A comment in that issue is that you can configure a JAAS Realm that always authenticates. How would that work?
It would be nice if tomcat-oidcauth provided a realm that can be configured that will always authenticate.

**Comment by ekkelenkamp** [comment]
I managed to implement a Jaas LoginModule that will handle the role assignment. Using a jaas.config file it is possible to keep the code in the web application and makes it very flexible. 
So everything seems to work fine.

**Comment by levahim** [comment]
Good job. Thanks!
