### ISSUE TITLE
Login Error when application is marked as distributable.

### ISSUE THREAD

**Issue by mark324** [boylesoftware/tomcat-oidcauth#37]
Hi.  I'm getting an error on login when the web.xml contains the distributable tag.  

The class Authorization is being set as an attribute on the session, but is not marked as Serializable.

    java.lang.IllegalArgumentException: setAttribute: Non-serializable attribute [org.bsworks.oidc.authorization]
        org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1411)
        org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1367)
        org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:137)
        org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse(BaseOpenIDConnectAuthenticator.java:1495)
        org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.performAuthentication(BaseOpenIDConnectAuthenticator.java:924)
        org.bsworks.catalina.authenticator.oidc.tomcat90.OpenIDConnectAuthenticator.doAuthenticate(OpenIDConnectAuthenticator.java:41)
        org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:631)

**Comment by levahim** [comment]
This has been addressed in version 2.3.1. Thanks!
