### ISSUE TITLE
Redirect immediately to Hosted UI

### ISSUE THREAD

**Issue by kingferiol** [boylesoftware/tomcat-oidcauth#39]
Hi and first of all let me say that I'm new to this topic.

I'm in a situation where I can't change the login page of my Web Application (can't change the source code) and I would like to understand if it is possible to force immediately the redirect for not authenticated request to the OP Hosted UI.

I can act just on my tomcat configurations

Of course, this is not an issue but just a request.

**Comment by levahim** [comment]
For an unauthenticated request the authenticator forwards to the login page configured for your web-app (`<login-config>` -> `<form-login-config>` -> `<form-login-page>` in your app's web.xml). It's just a URL. Tomcat provides you with different ways how you can specify exact behavior behind that URL, anything from overriding the deployment descriptor to using custom valves. I'd look for a solution somewhere in that space.
