### ISSUE TITLE
Surcharging processAuthResponse method

### ISSUE THREAD

**Issue by Houssem911** [boylesoftware/tomcat-oidcauth#41]
Hello,

First of all i would like to thank you for your library.
In my project i have developed a Tomcat 8.5 authentication valve that extends the main valve OpenIDConnectAuthenticator, in the valve classe i am overriding the method processAuthResponse everything works fine with the version 2.2.3. Recently we have decided to upgrade to Tomcat 8.5.57 and fourntly i have found that you already fix the compatibility issues in the 2.3.0 version but as the return type to the method processAuthResponse has been changed to the inner private type AuthedUser i can not override the method as this type is not visible in my extending class.
Could you please change the visibilté of the inner class AuthedUser so we can override the method processAuthResponse .

Thank you for your time and your great work.

Best regards,
Houssem

**Comment by levahim** [comment]
Good catch. Will fix.
