### ISSUE TITLE
Authentication with Microsoft Azure Active Directory

### ISSUE THREAD

**Issue by stephenobrien93** [boylesoftware/tomcat-oidcauth#42]
Hi,

I have set up tomcat-oidcauth v2.2.5 on Tomcat 8.5.33. I have configured 2 providers for authentication - Google and Microsoft. The Google authenticator works as expected - the user clicks a link on our login page, they are redirected to a Google sign in page, they  enter their details and if a corresponding user exists for them in our database, they are logged in. 

With Microsoft, we are redirected to the page as expected, and when we enter our details we are redirected to the error-login page. The URIs and Client Secrets match for the application in Azure AD, and the org.bsworks.oidc.error request attribute is null. 

Is there some extra configuration required for Microsoft Authentication? I have logging in my tomcat instance set to FINE, but I'm not seeing any logging relating to org.bsworks.

Thank you!

**Comment by levahim** [comment]
Something's wrong with your logging config--you should be able to see debug messages from org.bsworks. The debug messages should show you what's going on. FWIW, this is my logging.properties:

```
handlers = java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = org.apache.juli.OneLineFormatter

.handlers = java.util.logging.ConsoleHandler
.level = INFO

org.bsworks.level = FINE
org.apache.catalina.authenticator.level = FINE
```

For Azure AD 2 you may need to add `tokenEndpointAuthMethod: client_secret_post` to your provider config in the OIDC authenticator valve config. Otherwise, nothing special is needed for Microsoft.

**Comment by stephenobrien93** [comment]
Thanks for the quick response! I did a bit of investigating and ran into something of a brick wall, leaving this comment in case anyone else runs into these issues.

 I enabled the debugging like you said and set the `tokenEndpointAuthMethod: client_secret_post` into the OICD authenticator valve. I then got an `org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse the ID token issuer does not match` error. I did a bit of digging, and discovered the "iss" value from the `org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse` was `https://login.microsoftonline.com/{tenantid}/v2.0`. However, I'd configured the endpoint to be `https://login.microsoftonline.com/common/v2.0` in the OIDC Authenticator Valve Config. I found this (https://github.com/MicrosoftDocs/azure-docs/issues/38427) issue with Azure. It seems that for the `common` and `organizations` issuers, Azure returns an issuer in the form `https://login.microsoftonline.com/{tenantid}/v2.0`, which breaks the OICD spec. It looks like, in order to do the OpenID Authentication, we have to use the "consumers" issuer. This means that this will only work for personal Microsoft accounts, not work or school accounts.

Judging from the comments, it doesn't look like this issue will be resolved soon.

Thanks for your help!

**Comment by levahim** [comment]
You can set the auth config's `issuer` to https://login.microsoftonline.com/{tenantid}/v2.0 and then use `configurationDocumentUrl` to point it to https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration.

**Comment by stephenobrien93** [comment]
I'm not sure if that would work, as we intend to use this across multiple tenants.

**Comment by levahim** [comment]
OK, hard for me to evaluate your specific situation. Would you be able to formulate a feature request? If it's something simple we'll be happy to add it to the authenticator's functionality and then other folks who encounter a similar situation will benefit from it too.

**Comment by stephenobrien93** [comment]
Sure, is there some particular place I should post feature requests?

**Comment by levahim** [comment]
No, you can do it either here or create a new issue (will be easier to track).

**Comment by levahim** [comment]
Version 2.4.0 includes new config option `validateIssPattern`, which should resolve this issue.
