### ISSUE TITLE
Map Cognito groups to security roles?

### ISSUE THREAD

**Issue by smarkwal** [boylesoftware/tomcat-oidcauth#45]
I have a working integration with Amazon Cognito as provider. Cognito includes the groups of the authenticated user in the ID token as payload attribute "cognito:groups". What is the best way to map these groups to security roles so that Tomcat's role-based authorization works as expected, including calls to methods like request.isUserInRole(String)?

My first idea has been to implement a Realm that will generate a GenericPrincipal with role names matching the Cognito groups. Unfortunately, the Realm invoked by this Valve does not have access to the information in the ID token. All it gets is the username that was extracted from the ID token.

My second idea was to have a custom Realm that uses Cognito's REST API to fetch the information for the user with the given username, and then generate a GenericPrincipal with that username and the correct roles. I don't like this for two reasons. First, the Realm has to send another request to Cognito only to fetch information that was already fetched by the Valve before when getting the ID token. Second, this solution is also very Cognito-specific. In the best case, a solution would work with other providers as well, as long as they include group/role information in the ID token.

The third idea has been to implement another Valve that is hooked into the request processing chain after the Realm has been called. It would get the Cognito groups from the ID token in the session and then "enrich" the Principal in the request with additional roles.

The last idea would be to fork this Valve and implement this logic as a feature. Something that can be configured, like a "rolesClaim" configuration property. Like with the previous idea, the tricky thing here could be to add the extra roles to the Principal returned by the Valve.

Has someone ever done one of the above, or found another solution to this problem?

**Comment by smarkwal** [comment]
Another idea would be to fork the authenticator and adapt it so that it can pass the ID token (in encoded form) as argument for the username parameter to the Realm. A custom Realm then could "convert" the ID token into a GenericPrincipal by extracting the real username and the Cognito groups from the ID token.

**Comment by levahim** [comment]
Theoretically speaking, the logic for associating roles with users belongs in the realm. The authenticator is only responsible for authenticating the user. The authorization is in the realm (or the app itself). The realm is supposed to go lookup the user in the "user database" (which is Cognito user pool in your case) and return the principal object with all the relevant application-specific information, including the roles. So, your second idea is the most correct solution. Perhaps you could remediate the performance concern by using caching in the Cognito realm implementation?

**Comment by smarkwal** [comment]
Hi Lev,

Thank you for your feedback. I did some more research in the meantime and have found similar statements, most in the direction that one should use an ID token only as a "proof of identity" and that role-based authorization should be a separate concern.

Since our product has a local user database anyway, we now plan to set up a background job which will mirror/sync the users from Cognito into our user database. When a user logs in, we will use a realm that is looking up that user in our own user database. We have been using the same concept for years for LDAP-based authentication and it has worked very well.

Thanks again for your help, and have a nice weekend!
