### ISSUE TITLE
Documentation is not up-to-date

### ISSUE THREAD

**Issue by smarkwal** [boylesoftware/tomcat-oidcauth#46]
The example Valve configuration in README.md is not up-to-date. It features properties like "logoutUrl" or "postLogoutPage" which are never used in the source code.

Search for "logoutUrl": 
https://github.com/boylesoftware/tomcat-oidcauth/search?q=logoutUrl
-> Only found in README.md.

Search for "postLogoutPage": 
https://github.com/boylesoftware/tomcat-oidcauth/search?q=postLogoutPage
-> Only found in README.md.

**Comment by levahim** [comment]
It got into the docs from an experimental branch with IdP logout support functionality. Removed from the master branch. Thanks!
